eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8089/eureka/
keycloak:
  realm: cloud
  auth-server-url: http://localhost:11000/auth
  resource: cloud-service
  public-client: true