eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8089/eureka/
spring:
  zipkin:
    baseUrl: http://zipkin-server:9411
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-server
opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831