server:
  port: 8001
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: payments-topic
          content-type: application/json
          groups: shop
        paymemnts:
          destination: payments-topic
          content-type: application/json
          groups: shop
order-fee: 30
payments-service:
  name: payments-service
  resource: /payments