POST http://localhost:9000/payments
Accept: application/json
Content-Type: application/json

{
  "value": "1000 PLN"
}

###

GET http://localhost:9000/payments/18c6d029-7b42-4bbb-8853-2db7b9ff09b2
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "value": "1000 PLN"
}

###

GET http://localhost:8080/api/payments/2a769d8a-22a5-4538-9850-f4b3a70fd3bb
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/api/shop/orders
Accept: application/json
Content-Type: application/json

{
  "clientId": 1,
  "products": [
    {
       "id": 1
    }
  ]
}

###

GET http://localhost:8080/api/shop/orders/3
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8888/monitor
Content-Type: application/x-www-form-urlencoded

path=shop-service

###

POST http://localhost:8888/encrypt
Content-Type: text/html

20

###

POST http://localhost:8888/decrypt
Content-Type: text/html

cfce2b03cffc2f90948bff2c83ac4872d08d0c8830dc65150570c2e827aa527a

###

# rate(http_server_requests_seconds_count{uri="/payments"}[5m])
# Spring Boot Grafana dashboard id 4701
