version: '3'
services:
  zookeeper-server:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka-server:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper-server
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-server
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
  zipkin-server:
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411
  admin-server:
    image: training/admin-server
    restart: always
    environment:
      - PORT=8090
    ports:
      - 8090:8090
  configuration-server:
    image: training/configuration-server
    restart: always
    depends_on:
      - kafka-server
    ports:
      - 8888:8888
    environment:
      - ACTIVE_PROFILE=production
      - GIT_CONFIG_URI=https://github.com/landrzejewski/spring-cloud-training
      - KAFKA_SERVER=kafka-server
  discovery-server:
    image: training/discovery-server
    restart: always
    depends_on:
      - kafka-server
      - configuration-server
    ports:
      - 8089:8089
    environment:
      - ACTIVE_PROFILE=production
      - CONFIGURATION_SERVER_URI=http://configuration-server:8888
  gateway-server:
    image: training/gateway-server
    restart: always
    depends_on:
      - configuration-server
    ports:
      - 8080:8080
    environment:
      - ACTIVE_PROFILE=production
      - CONFIGURATION_SERVER_URI=http://configuration-server:8888
  payments-database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    volumes:
      - ./data/payments:/data
  shop-database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    volumes:
      - ./data/shop:/data
  payments-service:
    image: training/payments-service
    restart: always
    depends_on:
      - payments-database
      - kafka-server
      - discovery-server
      - configuration-server
    environment:
      - ACTIVE_PROFILE=production
      - CONFIGURATION_SERVER_URI=http://configuration-server:8888
  shop-service:
    image: training/shop-service
    restart: always
    depends_on:
      - shop-database
      - kafka-server
      - discovery-server
      - configuration-server
    environment:
      - ACTIVE_PROFILE=production
      - CONFIGURATION_SERVER_URI=http://configuration-server:8888